### ISSUE TITLE
Object.create(null) causes error

### ISSUE THREAD

**Issue by servel333** [flitbit/diff#49]
When diffing objects that are created using `Object.create(null)`, DeepDiff throws an exception.

```js
require('deep-diff')(Object.create(null), {});
// => TypeError: undefined is not a function
require('deep-diff')({}, Object.create(null));
// => TypeError: undefined is not a function
```

* Version: 0.3.2
* npm-shrinkwrap `"dependencies"."deep-diff"."resolved"`: `https://registry.npmjs.org/deep-diff/-/deep-diff-0.3.2.tgz`
* Exception line: https://github.com/flitbit/diff/blob/0.3.2/index.js#L132

Stack:
```
    at realTypeOf (node_modules/deep-diff/index.js:132:39)
    at deepDiff (node_modules/deep-diff/index.js:155:36)
    at accumulateDiff (node_modules/deep-diff/index.js:202:5)
    ...
```

**Comment by servel333** [comment]
Perhaps an additional check for `instanceof Object` is needed? (This idea needs a more in-depth examination)

```js
({}) instanceof Object // => true
Object.create(null) instanceof Object // => false
```

**Comment by flitbit** [comment]
Based on recent PRs, I'm of the opinion that this is no longer an issue:

```bash
im5k:deep-diff phillip$ node
> let diff = require('./')
undefined
> diff({wilbur: 'funky'}, Object.create(null))
[ DiffDeleted { kind: 'D', path: [ 'wilbur' ], lhs: 'funky' } ]
> diff(Object.create(null), {wilbur: 'funky'})
[ DiffNew { kind: 'N', path: [ 'wilbur' ], rhs: 'funky' } ]
```
