### ISSUE TITLE
Crash with objects without toString method

### ISSUE THREAD

**Issue by serkanserttop** [flitbit/diff#52]
I was getting the below crash.
This may not be frequent, but https://github.com/alunny/node-xcode produces objects that do not have `.toString` in their prototype.
I have a patch, I will create a PR.

    $PROJECT/node_modules/deep-diff/index.js:134
        } else if (/^\/.*\//.test(subject.toString())) {
                                          ^
    TypeError: undefined is not a function
        at realTypeOf ($PROJECT/node_modules/deep-diff/index.js:134:39)
        at deepDiff ($PROJECT/node_modules/deep-diff/index.js:157:16)
        at accumulateDiff ($PROJECT/node_modules/deep-diff/index.js:204:5)
        at Object.<anonymous> ($PROJECT/diff-xcode.js:19:19)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.runMain [as _onTimeout] (module.js:501:10)
        at Timer.listOnTimeout (timers.js:110:15)

**Comment by flitbit** [comment]
Fixed: https://github.com/flitbit/diff/commit/e56aeb461048e14374edcba093a7854813a2054f
