### ISSUE TITLE
Non-function toString will cause crash

### ISSUE THREAD

**Issue by scottnonnenberg** [flitbit/diff#71]
``` javascript
var deepDiff = require('deep-diff');

var left = {
  left: 'yes',
  right: 'no',
};

var right = {
  left: {
    toString: true,
  },
  right: 'no',
};

console.log(deepDiff(left, right));
```

Results in this:

```
node_modules/deep-diff/index.js:134
    } else if (typeof subject.toString !== 'undefined' && /^\/.*\//.test(subject.toString())) {
                                                                                 ^

TypeError: subject.toString is not a function
    at realTypeOf (node_modules/deep-diff/index.js:134:82)
    at deepDiff (node_modules/deep-diff/index.js:174:36)
    at node_modules/deep-diff/index.js:200:15
    at Array.forEach (native)
    at deepDiff (node_modules/deep-diff/index.js:197:17)
    at accumulateDiff (node_modules/deep-diff/index.js:221:5)
    at Object.<anonymous> (test.js:16:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

I encountered this when comparing two loaded `eslint` configs. The set of globals did include a non-function `toString` key. So this really does sometimes happen! :0)

**Comment by flitbit** [comment]
Fixed in lingering error in v0.3.5 on 2017-04-23
